build/glboost.js, src/js/Geometry.js, src/js/Mesh.js, src/js/math/Matrix44.js, src/js/shaders/HalfLambertShader.js, src/js/shaders/LambertShader.js, src/js/shaders/PhongShader.js
=> ライティングをカメラ座標系ではなく、ローカル座標系で行うようにする（バンプマッピング時を除く）

build/glboost.js, src/js/BlendShapeGeometry.js, src/js/ClassicMaterial.js, src/js/Element.js, src/js/Geometry.js, src/js/Mesh.js, src/js/Renderer.js, src/js/textures/AbstractTexture.js
対応しました。
examples/for_phina/primitives_2/index.html
のサンプルが体感でわかるくらい速くなりました。
=> Geometryを共有している複数のMeshにおいて、VBOやバインド処理の重複を無くす。

examples/index.html
Add an index page of the examples.
=> Add an index page of the examples.

package.json
Windows で動作するようビルドコマンドを見直しました。（「;」→「&&」に変更）
また、可読性向上の為、ビルド定義を細分化しました。
=> Add to support Windows.

examples/for_tmlib/blendshape/index.html, examples/for_tmlib/camera/index.html, examples/for_tmlib/index_buffer/index.html, examples/for_tmlib/multiple_contexts/index.html, examples/for_tmlib/multiple_render_targets/index.html, examples/for_tmlib/obj_mesh/index.html, examples/for_tmlib/obj_mesh_with_light/index.html, examples/for_tmlib/obj_mesh_with_mtl_string/index.html, examples/for_tmlib/texture/index.html, examples/index.html, examples/standalone/opacity/index.html
for_tmlib/blendshape/index.html               "basic example" -> "Blend Shape example"
for_tmlib/camera/index.html                   "basic example" -> "Camera example"
for_tmlib/index_buffer/index.html             "basic example" -> "Index Buffer example"
for_tmlib/multiple_contexts/index.html        "basic example" -> "Multiple Contexts example"
for_tmlib/multiple_render_targets/index.html  "basic example" -> "Multiple Render Targets example"
for_tmlib/obj_mesh/index.html                 "basic example" -> "Obj Mesh example"
for_tmlib/obj_mesh_with_light/index.html      "basic example" -> "Obj Mesh with Light example"
for_tmlib/obj_mesh_with_mtl_string/index.html "basic example" -> "Obj Mesh with MTL String example"
for_tmlib/texture/index.html                  "basic example" -> …
=> Fixed sample description.

examples/index.html
=> Fixed a problem of an index page of examples.

src/js/primitives/Sphere.js
球体のテクスチャが上下逆になる問題を修正。
> GLBoost で地球を回してみるテスト（改2）（失敗）
> http://jsdo.it/cx20/OqXi
=> Fix texture UV of sphere primitive.

src/js/primitives/Sphere.js
sphere クラスのコンストラクタ引数の仕様変更を提案。
第４引数の customVertexAttributes が現在未使用となっているが、代わりに Cube と同様に、vertexColor を引数としたい。
＜理由＞
ボールの色を変更したいケースがある為。
=> Change sphere function constructor.

examples/for_phina/multiple_render_targets/index.html
=> Use blendWeights of BlendShapeGeometry.

build/glboost.js, src/low_level/shaders/Shader.js, src/middle_level/loader/GLTFLoader.js
Fix PremultipliedAlpha of glTF1 Loader & Shader.js.
=> Fix PremultipliedAlpha of glTF1 Loader & Shader.js

build/glboost.js, src/globals.js
Fix a display bug caused by previous GLBoost Constants Proccess changed.
=> Fix a display bug caused by previous GLBoost Constants Proccess changed

build/glboost.js, src/middle_level/glboost_include.js, src/middle_level/loader/FormatDetector.js
=> Add FormatDetector.js

build/glboost.js, examples/test/loading_gltf/index.html, src/middle_level/Renderer.js
Add doRenderLoop and doConvenientRenderLoop and stopRenderLoop methods to Renderer.js.
=> Add doRenderLoop and doConvenientRenderLoop and stopRenderLoop methods to Renderer.js

build/glboost.js, src/low_level/geometries/BlendShapeGeometry.js, src/low_level/geometries/Geometry.js, src/middle_level/Renderer.js, src/middle_level/draw_kickers/DrawKickerWorld.js, src/middle_level/elements/meshes/M_Mesh.js
Refactor method of argument passing
=> Refactor method of argument passing

build/glboost.js, examples/test/loading_gltf/index.html, src/low_level/geometries/BlendShapeGeometry.js, src/low_level/geometries/Geometry.js, src/middle_level/Renderer.js, src/middle_level/draw_kickers/DrawKickerWorld.js, src/middle_level/elements/meshes/M_Mesh.js
=> Basic support of WebVR

build/glboost.js, examples/test/loading_gltf/index.html, examples/test/loading_gltf_skinning_anim/index.html, src/middle_level/Renderer.js
Improve the process of enabling WebVR.
=> Improve the process of enabling WebVR

build/glboost.js, src/middle_level/loader/GLTFLoader.js
Enabled to specify default shader as string.
=> Enabled to specify default shader as string.

build/glboost.js, src/middle_level/Renderer.js, src/middle_level/draw_kickers/DrawKickerWorld.js
=> Improve handling of WebVR.

build/glboost.js, src/low_level/materials/L_AbstractMaterial.js, src/middle_level/elements/M_Element.js, src/middle_level/elements/M_Group.js
Implement readyForDiscard method to some classes.
=> Implement readyForDiscard method to some classes.

build/glboost.js, src/middle_level/Renderer.js
Improve WebVR process and error handling.
=> Improve WebVR process and error handling.

build/glboost.js, src/middle_level/loader/GLTFLoader.js
Add loadOptions to gltf1.0 asset.extras
=> Add loadOptions to gltf1.0 asset.extras

build/glboost.js, src/globals.js, src/low_level/elements/L_Element.js, src/low_level/misc/AnimationUtil.js, src/middle_level/loader/GLTFLoader.js
Support 'STEP' Interpolation Method
=> Support 'STEP' Interpolation Method

src/middle_level/loader/FormatDetector.js, src/middle_level/loader/GLTF2Loader.js, src/middle_level/loader/GLTFLoader.js, src/middle_level/loader/ModelConverter.js
Improve loading steps of glTF loaders
=> Improve loading steps of glTF loaders

src/middle_level/loader/GLTF2Loader.js
Improved glb file loading even if it depends on external file in glTF2Loader
=> Improved glb file loading even if it depends on external file in glTF2Loader

src/low_level/elements/L_Element.js, src/middle_level/elements/M_Element.js, src/middle_level/elements/M_Group.js
add few flowtype definition.
could you check it?
=> add flowtype definition
